[package]
name = "util_bevy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5.0"
bevy_prototype_lyon = "0.3.1"
lyon_path = "0.17.7"
rand = "0.8.4"

skitspel = { path = "../skitspel" }
